import ABIS from './abis';

module.exports = Object.freeze({
  ESCROWS: {
    address: { RTO: process.env.RTO_ESCROW_CONTRACT_ADDRESS },
    abi: ABIS.ESCROWS,
  },
  VAULT: {
    address: process.env.VAULT_CONTRACT_ADDRESS,
    abi: ABIS.VAULT,
  },
  REGISTRY: {
    address: process.env.REGISTRY_CONTRACT_ADDRESS,
    abi: ABIS.REGISTRY,
  },
  PROPOSAL: {
    address: process.env.PROPOSAL_CONTRACT_ADDRESS,
    abi: ABIS.PROPOSAL,
  },
  PAYMENT: {
    address: process.env.PAYMENT_CONTRACT_ADDRESS,
    abi: ABIS.PAYMENT,
  },
  JOINT_ACCOUNT: {
    address: null,
    abi: ABIS.JOINT_ACCOUNT,
  },
  JOINT_ACCOUNT_FACTORY: {
    address: process.env.JOINT_ACCOUNT_FACTORY_ADDRESS,
    abi: ABIS.JOINT_ACCOUNT_FACTORY,
  },
  JOINT_ACCOUNT_BEACON: {
    address: process.env.JOINT_ACCOUNT_BEACON_ADDRESS,
    abi: ABIS.JOINT_ACCOUNT_BEACON,
  },
  SWAP: {
    address: process.env.SWAP_CONTRACT_ADDRESS,
    abi: ABIS.SWAP,
  },
  SWAP_ORACLE: {
    address: process.env.SWAP_MARKET_RATE_ORACLE_ADDRESS,
    abi: ABIS.SWAP_ORACLE,
  },
  TOKENS: {
    RTC: {
      address: process.env.RTC_CONTRACT_ADDRESS,
      abi: ABIS.RTC,
      admin: process.env.RTC_ADMIN_ADDRESS,
      kmsKeyId: process.env.RTC_ADMIN_KEY_ID,
      decimals: 18,
      chain: 'RTC',
    },
    RTO: {
      address: process.env.RTO_CONTRACT_ADDRESS,
      abi: ABIS.RTO,
      admin: process.env.RTO_ADMIN_ADDRESS,
      kmsKeyId: process.env.RTO_ADMIN_KEY_ID,
      decimals: 18,
      chain: 'RTC',
    },
    WETH: {
      address: process.env.WETH_CONTRACT_ADDRESS,
      abi: ABIS.WERC20,
      admin: process.env.ETH_ADMIN_ADDRESS,
      kmsKeyId: process.env.ETH_ADMIN_KEY_ID,
      decimals: 18,
      chain: 'RTC',
    },
    WUSDT: {
      address: process.env.WUSDT_CONTRACT_ADDRESS,
      abi: ABIS.WERC20,
      admin: process.env.USDT_ADMIN_ADDRESS,
      kmsKeyId: process.env.USDT_ADMIN_KEY_ID,
      decimals: 18,
      chain: 'RTC',
    },
    WUSDC: {
      address: process.env.WUSDC_CONTRACT_ADDRESS,
      abi: ABIS.WERC20,
      admin: process.env.USDC_ADMIN_ADDRESS,
      kmsKeyId: process.env.USDC_ADMIN_KEY_ID,
      decimals: 18,
      chain: 'RTC',
    },
    WBNB: {
      address: process.env.WBNB_CONTRACT_ADDRESS,
      abi: ABIS.WERC20,
      admin: process.env.BNB_ADMIN_ADDRESS,
      kmsKeyId: process.env.BNB_ADMIN_KEY_ID,
      decimals: 18,
      chain: 'RTC',
    },
    WBTC: {
      address: process.env.WBTC_CONTRACT_ADDRESS,
      abi: ABIS.WERC20,
      admin: process.env.WBTC_ADMIN_ADDRESS,
      kmsKeyId: process.env.WBTC_ADMIN_KEY_ID,
      decimals: 18,
      chain: 'RTC',
    },
    ETH: {
      address: null,
      abi: null,
      admin: process.env.ETH_ADMIN_ADDRESS,
      kmsKeyId: process.env.ETH_ADMIN_KEY_ID,
      decimals: 18,
      chain: 'ETH',
    },
    USDT: {
      address: process.env.USDT_CONTRACT_ADDRESS,
      abi: ABIS.ERC20,
      admin: process.env.USDT_ADMIN_ADDRESS,
      kmsKeyId: process.env.USDT_ADMIN_KEY_ID,
      decimals: 6,
      chain: 'ETH',
    },
    USDC: {
      address: process.env.USDC_CONTRACT_ADDRESS,
      abi: ABIS.ERC20,
      admin: process.env.USDC_ADMIN_ADDRESS,
      kmsKeyId: process.env.USDC_ADMIN_KEY_ID,
      decimals: 6,
      chain: 'ETH',
    },
    ERTC: {
      address: process.env.ERTC_CONTRACT_ADDRESS,
      abi: ABIS.ERC20,
      admin: process.env.ERTC_ADMIN_ADDRESS,
      kmsKeyId: process.env.ERTC_ADMIN_KEY_ID,
      decimals: 18,
      chain: 'ETH',
    },
    BNB: {
      address: null,
      abi: null,
      admin: process.env.BNB_ADMIN_ADDRESS,
      kmsKeyId: process.env.BNB_ADMIN_KEY_ID,
      decimals: 18,
      chain: 'BNB',
    },
    BTC: {
      address: null,
      abi: null,
      admin: process.env.BTC_ADMIN_ADDRESS,
      kmsKeyId: process.env.BTC_ADMIN_KEY_ID,
      decimals: 8,
      chain: 'BTC',
    },
    KWD: {
      address: process.env.KWD_CONTRACT_ADDRESS,
      abi: ABIS.WERC20,
      admin: process.env.DIGITAL_CURRENCY_ADMIN_ADDRESS,
      kmsKeyId: process.env.DIGITAL_CURRENCY_ADMIN_KEY_ID,
      decimals: 18,
      chain: 'RTC',
    },
    BHD: {
      address: process.env.BHD_CONTRACT_ADDRESS,
      abi: ABIS.WERC20,
      admin: process.env.DIGITAL_CURRENCY_ADMIN_ADDRESS,
      kmsKeyId: process.env.DIGITAL_CURRENCY_ADMIN_KEY_ID,
      decimals: 18,
      chain: 'RTC',
    },
    OMR: {
      address: process.env.OMR_CONTRACT_ADDRESS,
      abi: ABIS.WERC20,
      admin: process.env.DIGITAL_CURRENCY_ADMIN_ADDRESS,
      kmsKeyId: process.env.DIGITAL_CURRENCY_ADMIN_KEY_ID,
      decimals: 18,
      chain: 'RTC',
    },
    JOD: {
      address: process.env.JOD_CONTRACT_ADDRESS,
      abi: ABIS.WERC20,
      admin: process.env.DIGITAL_CURRENCY_ADMIN_ADDRESS,
      kmsKeyId: process.env.DIGITAL_CURRENCY_ADMIN_KEY_ID,
      decimals: 18,
      chain: 'RTC',
    },
    KYD: {
      address: process.env.KYD_CONTRACT_ADDRESS,
      abi: ABIS.WERC20,
      admin: process.env.DIGITAL_CURRENCY_ADMIN_ADDRESS,
      kmsKeyId: process.env.DIGITAL_CURRENCY_ADMIN_KEY_ID,
      decimals: 18,
      chain: 'RTC',
    },
    GBP: {
      address: process.env.GBP_CONTRACT_ADDRESS,
      abi: ABIS.WERC20,
      admin: process.env.DIGITAL_CURRENCY_ADMIN_ADDRESS,
      kmsKeyId: process.env.DIGITAL_CURRENCY_ADMIN_KEY_ID,
      decimals: 18,
      chain: 'RTC',
    },
    CHF: {
      address: process.env.CHF_CONTRACT_ADDRESS,
      abi: ABIS.WERC20,
      admin: process.env.DIGITAL_CURRENCY_ADMIN_ADDRESS,
      kmsKeyId: process.env.DIGITAL_CURRENCY_ADMIN_KEY_ID,
      decimals: 18,
      chain: 'RTC',
    },
    USD: {
      address: process.env.USD_CONTRACT_ADDRESS,
      abi: ABIS.WERC20,
      admin: process.env.DIGITAL_CURRENCY_ADMIN_ADDRESS,
      kmsKeyId: process.env.DIGITAL_CURRENCY_ADMIN_KEY_ID,
      decimals: 18,
      chain: 'RTC',
    },
    CAD: {
      address: process.env.CAD_CONTRACT_ADDRESS,
      abi: ABIS.WERC20,
      admin: process.env.DIGITAL_CURRENCY_ADMIN_ADDRESS,
      kmsKeyId: process.env.DIGITAL_CURRENCY_ADMIN_KEY_ID,
      decimals: 18,
      chain: 'RTC',
    },
    EUR: {
      address: process.env.EUR_CONTRACT_ADDRESS,
      abi: ABIS.WERC20,
      admin: process.env.DIGITAL_CURRENCY_ADMIN_ADDRESS,
      kmsKeyId: process.env.DIGITAL_CURRENCY_ADMIN_KEY_ID,
      decimals: 18,
      chain: 'RTC',
    },
    MXN: {
      address: process.env.MXN_CONTRACT_ADDRESS,
      abi: ABIS.WERC20,
      admin: process.env.DIGITAL_CURRENCY_ADMIN_ADDRESS,
      kmsKeyId: process.env.DIGITAL_CURRENCY_ADMIN_KEY_ID,
      decimals: 18,
      chain: 'RTC',
    },
    INR: {
      address: process.env.INR_CONTRACT_ADDRESS,
      abi: ABIS.WERC20,
      admin: process.env.DIGITAL_CURRENCY_ADMIN_ADDRESS,
      kmsKeyId: process.env.DIGITAL_CURRENCY_ADMIN_KEY_ID,
      decimals: 18,
      chain: 'RTC',
    },
    NOK: {
      address: process.env.NOK_CONTRACT_ADDRESS,
      abi: ABIS.WERC20,
      admin: process.env.DIGITAL_CURRENCY_ADMIN_ADDRESS,
      kmsKeyId: process.env.DIGITAL_CURRENCY_ADMIN_KEY_ID,
      decimals: 18,
      chain: 'RTC',
    },
    SEK: {
      address: process.env.SEK_CONTRACT_ADDRESS,
      abi: ABIS.WERC20,
      admin: process.env.DIGITAL_CURRENCY_ADMIN_ADDRESS,
      kmsKeyId: process.env.DIGITAL_CURRENCY_ADMIN_KEY_ID,
      decimals: 18,
      chain: 'RTC',
    },
    DKK: {
      address: process.env.DKK_CONTRACT_ADDRESS,
      abi: ABIS.WERC20,
      admin: process.env.DIGITAL_CURRENCY_ADMIN_ADDRESS,
      kmsKeyId: process.env.DIGITAL_CURRENCY_ADMIN_KEY_ID,
      decimals: 18,
      chain: 'RTC',
    },
  },
});